### PR TITLE
fix: throw error when flags do not match pattern

### LINKED ISSUE #829: Flag silently ignored when contains invalid characters
**Describe the bug**

>Flags Must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters

If my CI suite accidentally contains a slash or some other character, the flag is silently dropped.

**To Reproduce**
1. Use uploader v0.2.4
2. send a flag as `-F ci/js-unit-tests`
3. The upload succeeds but the flag is blank

**Expected behavior**

I would expect it to bail out with "Invalid flag: flags Must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters"

**Additional context**

If you think this is too much of a BC break, I could accept this being hidden behind a flag like `CODECOV_STRICT_FLAGS=1` or something.

### PR DESCRIPTION
**Pull request by drazisil-codecov**
Prior behavior was to strip out invalid flag names. The validation function will now throw.

Fixes #829

### CODE REVIEW

File: src/helpers/validate.ts [hunk 1]
```diff
@@ -14,10 +14,15 @@ export function validateURL(url: string): boolean {
...
   // eslint-disable-next-line no-useless-escape
   const mask = /^[\w\.\-]{1,45}$/
-  return mask.test(flags)
+  if (flag.length !== 0 && mask.test(flag) !== true) {
+    throw new Error(
+      `Flags must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters. Received ${flag}`,
+    )
+  }
+  return true
 }
```
Comment (mitchell-codecov) [inline src/helpers/validate.ts:26]:
```suggestion
export function isValidFlag(flag: string): boolean {
  return flag.length > 0 && mask.test(flag)
}

export function validateFlags(flags: string[]): void {
  const invalidFlags = flags.filter(isValidFlag)
  
  if (invalidFlags.length > 0) {
    throw new Error(
      `Flags must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters. Received ${flags.join(',')}`,
    )
  }
}
```

File: src/helpers/validate.ts [hunk 2]
```diff
@@ -14,10 +14,15 @@ export function validateURL(url: string): boolean {
   return validator.isURL(url, { require_protocol: true })
 }
 
-export function validateFlags(flags: string): boolean {
+export function validateFlags(flag: string): boolean {
```
Comment (mitchell-codecov) [inline src/helpers/validate.ts:17]:
```suggestion
export function validateFlags(flags: string[]): void {
```

File: src/helpers/validate.ts [hunk 3]
```diff
@@ -14,10 +14,15 @@ export function validateURL(url: string): boolean {
...
   // eslint-disable-next-line no-useless-escape
   const mask = /^[\w\.\-]{1,45}$/
```
Comment (mitchell-codecov) [inline src/helpers/validate.ts:19]:
```suggestion
```

File: src/helpers/validate.ts [hunk 4]
```diff
@@ -14,10 +14,15 @@ export function validateURL(url: string): boolean {
...
-  return mask.test(flags)
+  if (flag.length !== 0 && mask.test(flag) !== true) {
```
Comment (mitchell-codecov) [inline src/helpers/validate.ts:20]:
```suggestion
  const invalidFlags = flags.filter(isValidFlag)

  if (invalidFlags.length > 0) {
```

File: src/helpers/validate.ts [hunk 5]
```diff
@@ -14,10 +14,15 @@ export function validateURL(url: string): boolean {
...
+    throw new Error(
+      `Flags must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters. Received ${flag}`,
```
Comment (mitchell-codecov) [inline src/helpers/validate.ts:22]:
```suggestion
      `Flags must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters. Received ${flags}`,
```

File: src/helpers/validate.ts [hunk 6]
```diff
@@ -14,10 +14,15 @@ export function validateURL(url: string): boolean {
...
+    )
+  }
+  return true
```
Comment (mitchell-codecov) [inline src/helpers/validate.ts:25]:
```suggestion
```

**Review by mitchell-codecov — CHANGES_REQUESTED** [review]

File: src/helpers/validate.ts (hunk 2 above)
Comment (drazisil-codecov) [reply src/helpers/validate.ts:17]: This is being passed a single flag as part of a filter command, I believe, @mitchell-codecov

File: src/helpers/validate.ts (hunk 3 above)
Comment (drazisil-codecov) [reply src/helpers/validate.ts:19]: @mitchell-codecov Why are you deleting the mask?

**Review by mitchell-codecov — APPROVED** [review]
