### PR TITLE
[CESD-492] always use block list

### LINKED ISSUE #504: [CESD-492] Uploader should always use it's block list
**Describe the bug**
When the `-f` flag  is used, the uploader skips filtering through the blocklist https://github.com/codecov/uploader/blob/38a46e63bdee859f01abead19f71caa3a520641d/src/helpers/files.ts#L28-L151

**Additional context**
In addition to fixing this bug, rename the block list

### PR DESCRIPTION
**Pull request by drazisil-codecov**
Closes #504
Renames blocklist

### CODE REVIEW

File: src/helpers/logger.ts [hunk 1]
```diff
@@ -41,3 +41,30 @@ export function logError(message: string): void {
 export function info(message: string): void {
   console.log(`[${_getTimestamp()}] ['info'] ${message}`)
 }
+
+export class UploadLogger {
```
Comment (mitchell-codecov) [inline src/helpers/logger.ts:45]: A future PR may want to utilize [the built-in Console class](https://nodejs.org/api/console.html#class-console).

File: src/index.ts [hunk 2]
```diff
@@ -21,6 +22,7 @@ import {
   readCoverageFile,
   removeFile,
 } from './helpers/files'
+import { arch } from 'os'
```
Comment (mitchell-codecov) [inline src/index.ts:25]:
```suggestion
```

This appears to be unused.

File: src/index.ts [hunk 3]
```diff
@@ -77,6 +79,10 @@ export async function main(
   args: UploaderArgs,
 ): Promise<void | Record<string, unknown>> {
 
+  if (args.verbose) {
```
Comment (mitchell-codecov) [inline src/index.ts:82]: This is a great use of the feature flag pattern.

File: test/helpers/files.test.ts [hunk 4]
```diff
@@ -3,6 +3,7 @@ import fs from 'fs'
 import childProcess from 'child_process'
 import * as fileHelpers from '../../src/helpers/files'
 import mock from 'mock-fs'
+import path from 'path/posix'
```
Comment (mitchell-codecov) [inline test/helpers/files.test.ts:6]:
```suggestion
```

This appears to be unused.

File: src/helpers/files.ts [hunk 5]
```diff
@@ -332,3 +333,26 @@ export function removeFile(projectRoot: string, filePath: string): void {
     }
   })
 }
+export function getBlocklist() {
+  return [...manualBlocklist(), ...globBlocklist()]
+}
+
+export function cleanCoverageFilePaths(projectRoot: string, paths: string[], ignoreGlobs: string[]) {
```
Comment (mitchell-codecov) [inline src/helpers/files.ts:340]:
```suggestion
export function cleanCoverageFilePaths(projectRoot: string, paths: string[], ignoreGlobs: string[]): string[] {
```

File: src/helpers/files.ts [hunk 6]
```diff
@@ -332,3 +333,26 @@ export function removeFile(projectRoot: string, filePath: string): void {
     }
   })
 }
+export function getBlocklist() {
```
Comment (mitchell-codecov) [inline src/helpers/files.ts:336]:
```suggestion
export function getBlocklist(): string[] {
```

File: src/helpers/files.ts [hunk 7]
```diff
@@ -332,3 +333,26 @@ export function removeFile(projectRoot: string, filePath: string): void {
...
+  }))]
+
+  if (coverageFilePaths.length === 0) {
+    throw new Error('Error while cleaning paths. No paths matched existing files!')  
+  }
+
+  const ignoredFiles = micromatch(coverageFilePaths, ignoreGlobs)
+
+  const filesAfterCheckingIgnore = coverageFilePaths.filter(path => {
+    return !ignoredFiles.includes(path)
```
Comment (mitchell-codecov) [inline src/helpers/files.ts:353]:
```suggestion
    return !ignoredFiles.has(path)
```

**Review by mitchell-codecov — APPROVED** [review]

File: src/index.ts (hunk 2 above)
Comment (drazisil-codecov) [reply src/index.ts:25]: I don't even know what it's doing there 🤷‍♀️

File: src/helpers/files.ts (hunk 7 above)
Comment (drazisil-codecov) [reply src/helpers/files.ts:353]: `has()` does not exist on `string[]` What is the difference?

File: src/index.ts (hunk 2 above)
Comment (mitchell-codecov) [reply src/index.ts]: VS Code autocomplete probably brought it in.

File: src/helpers/files.ts (hunk 7 above)
Comment (mitchell-codecov) [reply src/helpers/files.ts:353]: You're correct. `has()` exists on instances of the Set class. It has a sublinear runtime complexity but, since `ignoredFiles` is an array, it can't actually be used in this case.
