### PR TITLE
Fix: @returns JSDoc annotations for string

### LINKED ISSUE #153: `@returns` JSDoc annotations are incorrect
`string` should be `{string}`, etc. This issue will likely require a project-wide refactor due to its pervasiveness.

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #153

### CODE REVIEW

File: src/ci_providers/provider_azurepipelines.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ function _getSlug(inputs) {
  * Generates and return the serviceParams object
  *
  * @param {args: {}, envs: {}} inputs an object of arguments and enviromental variable key/value pairs
- * @returns { branch: String, build: String, buildURL: String, commit: String, job: String, pr: String, service: String, slug: String}
+ * @returns { branch: String, build: {String}, buildURL: {String}, commit: {String}, job: {String}, pr: {String}, service: {String}, slug: {String}}
```
Comment (RA80533) [inline src/ci_providers/provider_azurepipelines.js:91]:
```suggestion
 * @returns {{ branch: string, build: string, buildURL: string, commit: string, job: string, pr: string, service: string, slug: string }}
```

**Review by drazisil-codecov — APPROVED** [review]
I notice in some places there is `String` and in others there is `string`. I think these have different meanings and they all should be `string` https://jsdoc.app/tags-type.html

Do you mind changing them over? If not, I'll just open another issue and merge this one :)

**Comment by Patil2099** [comment]
I will make the changes in a couple of minutes.

**Comment by Patil2099** [comment]
I think it is mergeable now. @drazisil-codecov

**Review by drazisil-codecov — APPROVED** [review]
Awesome! Thank you very much for the PR, @Patil2099 ! 🚀
