### PR TITLE
Issue 22

### LINKED ISSUE #22: -f flag can not handle an absolute path
**Describe the bug**
-f flag can not handle an absolute path. Since it appends `./` to the path, the path becomes invalid

**To Reproduce**
1. Pass the `-f` flag a file path that starts with `/`
2. See error

**Expected behavior**
If the passed path starts with a `/` the app should not prefix with `./`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by drazisil**
closes #22 

Add detection for absolute paths and do not prefix them with `./`

Add dry-run tests for same.

### CODE REVIEW

File: src/helpers/files.js [hunk 1]
```diff
@@ -169,5 +182,6 @@ module.exports = {
   fetchGitRoot,
   parseGitIgnore,
   getCoverageFiles,
-  coverageFilePatterns
+  coverageFilePatterns,
+  getFilePath
```
Comment (thomasrockhu) [inline src/helpers/files.js:186]: super nit: if possible, if things can be alphabetized, I like them alphabetized

Comment (drazisil) [reply src/helpers/files.js:186]: PRs welcome ;)
